<?php

/**
 * @file
 * Contains explore_drupal.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function explore_drupal_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the explore_drupal module.
    case 'help.page.explore_drupal':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Testing Functionality of Drupal 8') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function explore_drupal_theme() {
  return [
    'explore_drupal' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_page_attachments.
 */
function explore_drupal_page_attachments_alter(&$build) {
  $build['#attached']['library'][] = 'explore_drupal/cuddly-slider';
  $build['#attached']['drupalSettings']['explore_drupal']['cuddlySlider']['foo'] = '123';
}
